### ISSUE TITLE
Bug: narrow browser window masks button clicks

### ISSUE THREAD

**Issue by kcritzsalient** [the-pudding/pass-the-mic#58]
Reproduction step:  set Chrome window to half the width of a laptop screen  (~5 tabs visible) and start a meeting.

Expected behavior: I should be able to click on the lower bar of control buttons like "turn off microphone" and "turn off video".  I should be able to see tooltip hints for these buttons.

Observed behavior: Tooltips do not display, and buttons do not respond to clicks.  Buttons still respond to keyboard commands like command-D and command-e

Impact:  Since installing this plugin, I experience more embarrassing "you're on mute" incidents.

**Comment by polygraph-umg** [comment]
thanks! this should be fixed on the next release (v0.3.1) - 24 hours from now after you relaunch the browser and it updates extensions.
